### ISSUE TITLE
Fix nightly builds

### ISSUE THREAD

**Issue by jl-wynen** [scipp/ess#306]
Nightly builds are broken because the Amor files can no longer be loaded. The error occurs in `scippnexus/nxtransformations.py:62`:
```python
return sc.vector(value=self.attrs.get('vector'))
```
where `self.attrs.get('vector') is None`.

I don't know whether this is a problem with the file or ScippNeXus.

**Comment by nvaytet** [comment]
Strange, I doubt the files have changed.

[This PR in scippnexus](https://github.com/scipp/scippnexus/pull/231) was merged on september 4th, and the first failing nightly build is on september 5th... So I am guessing that's the culprit?

**Comment by jl-wynen** [comment]
Maybe. But I don't see how logs (in that PR) and transforms (the failing code) are connected.

**Comment by jokasimr** [comment]
From a glance it seems like the attribute `vector` did exist on the data-group (that's why it worked before), but not on the data-array, so when we replace the data-group with the data-array we lose the attributes.

It's worth mentioning that the nexus files in this example are broken. Particularly `NXlog` don't look like what we expect.

**Comment by MridulS** [comment]
https://github.com/scipp/scippnexus/pull/231/ is indeed the issue, reverting to the last commit without the change works fine with the current notebook.

**Comment by jokasimr** [comment]
This is now fixed in scippnexus by being more graceful when encountering broken files.

But to make the nightly pass we need to release scippnexus ([~in progress~ done](https://github.com/scipp/scippnexus/releases/tag/24.09.1)) and lower bound the scippnexus dependency in essreflectometry to that release.

**Comment by MridulS** [comment]
https://github.com/scipp/essreflectometry/actions/workflows/nightly_at_main.yml is happy now.
